GET http://localhost:8080/api/notes

### 200
GET http://localhost:8080/api/notes/63be87b512112c6a71c74c4d

### 404 not found
GET http://localhost:8080/api/notes/63be87b512112c6a71c74c11

### 400 error
GET http://localhost:8080/api/notes/xxx

### 404 unknown endpoint
GET http://localhost:8080/xxx

### delete
DELETE http://localhost:8080/api/notes/63d6736d6dbf2ea1da85abc4

### create with userId (ログインしてデジタル署名･トークン発行が必要)
POST http://localhost:8080/api/notes
Content-Type: application/json
Authorization: Bearer xxx

{
  "content": "VSCode is a good tool for testing a REST-api with Bearer token",
  "important": true,
  "userId": "63d92d65bc17070e8f1631bb",
  "dammy": "dammy"
}

### create validation error
POST http://localhost:8080/api/notes
Content-Type: application/json

{
  "content": "lol",
  "important": true
}

### change note content and important
PUT http://localhost:8080/api/notes/63a04f22fdc2c907f32e80ff
Content-Type: application/json

{
  "content": "html is easy lol",
  "important": false
}
